# Generated by Django 5.0.6 on 2026-06-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_file',
            field=models.FileField(blank=True, help_text='Supplemental materials for the lesson (e.g. PDF)', null=True, upload_to='lessons/files/%Y/%m/', verbose_name='Lesson File'),
        ),
    ]
