# Generated by Django 6.0.6 on 2026-06-16 18:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_lesson_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Display title shown to students', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about the summary')),
                ('file', models.FileField(help_text='The downloadable file (PDF, DOCX, etc.)', upload_to='summaries/%Y/%m/')),
                ('academic_level', models.CharField(choices=[('level_1', 'المستوى الأول'), ('level_2', 'المستوى الثاني'), ('level_3', 'المستوى الثالث'), ('level_4', 'المستوى الرابع')], db_index=True, help_text='Academic year/level this summary belongs to', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Subject or topic (e.g. خرائط, جيولوجيا)', max_length=100)),
                ('is_published', models.BooleanField(default=False, help_text='Only published summaries are visible to students')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times this file has been downloaded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Summary',
                'verbose_name_plural': 'Summaries',
                'db_table': 'summaries',
                'ordering': ['academic_level', '-created_at'],
            },
        ),
    ]
