# Generated by Django 5.0.6 on 2026-06-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-created_at'], 'verbose_name': 'Summary', 'verbose_name_plural': 'Summaries'},
        ),
        migrations.RemoveField(
            model_name='summary',
            name='academic_level',
        ),
        migrations.AddField(
            model_name='summary',
            name='source',
            field=models.CharField(blank=True, help_text='Name of the reference or source (e.g. كتاب الخرائط)', max_length=255),
        ),
        migrations.AddField(
            model_name='summary',
            name='source_url',
            field=models.URLField(blank=True, help_text='Optional URL link to the source/reference'),
        ),
    ]
