# Generated by Django 5.0.6 on 2026-06-24 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_academic_level_add_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Display title for this metadata entry', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the metadata')),
                ('category', models.CharField(blank=True, help_text='Category or type (e.g. بيانات جغرافية, بيانات سكانية)', max_length=100)),
                ('source', models.CharField(blank=True, help_text='Name of the reference or source', max_length=255)),
                ('source_url', models.URLField(blank=True, help_text='Optional URL link to the source')),
                ('file', models.FileField(blank=True, help_text='Optional attached file (PDF, DOCX, etc.)', upload_to='metadata/%Y/%m/')),
                ('is_published', models.BooleanField(default=True, help_text='Only published entries are visible publicly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metadata Entry',
                'verbose_name_plural': 'Metadata Entries',
                'db_table': 'metadata_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpatialDataEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Display title for this spatial data entry', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the spatial data')),
                ('latitude', models.FloatField(help_text='Latitude coordinate (e.g. 30.0444 for Cairo)')),
                ('longitude', models.FloatField(help_text='Longitude coordinate (e.g. 31.2357 for Cairo)')),
                ('data_type', models.CharField(choices=[('point', 'نقطة'), ('line', 'خط'), ('polygon', 'مضلع'), ('layer', 'طبقة')], default='point', help_text='Type of spatial data', max_length=50)),
                ('category', models.CharField(blank=True, help_text='Category (e.g. مواقع أثرية, حدود إدارية)', max_length=100)),
                ('source', models.CharField(blank=True, help_text='Name of the reference or source', max_length=255)),
                ('source_url', models.URLField(blank=True, help_text='Optional URL link to the source')),
                ('file', models.FileField(blank=True, help_text='Optional spatial file (Shapefile, GeoJSON, KML, etc.)', upload_to='spatial/%Y/%m/')),
                ('geojson_data', models.JSONField(blank=True, help_text='Inline GeoJSON data for map rendering', null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Only published entries are visible publicly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spatial Data Entry',
                'verbose_name_plural': 'Spatial Data Entries',
                'db_table': 'spatial_data_entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
