# Generated by Django 6.0.6 on 2026-06-16 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('system', 'نظام'), ('admin', 'إدارية')], db_index=True, default='system', help_text='Notification origin: system-generated or admin-created', max_length=10)),
                ('title', models.CharField(help_text='Short notification title', max_length=255)),
                ('message', models.TextField(help_text='Full notification message body')),
                ('link', models.CharField(blank=True, help_text='Optional deep-link URL (e.g. /courses/geo101)', max_length=500)),
                ('is_global', models.BooleanField(default=True, help_text='If True, broadcast to all active users')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin user who created this notification (null for system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether the user has read this notification')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when the user read the notification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entries', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'db_table': 'user_notifications',
                'ordering': ['-notification__created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'notification'), name='unique_user_notification')],
            },
        ),
    ]
